---

- name: Make sure files exist
  file:
    path: "{{ item }}"
    state: present
    mode: 0664
  with_items:
  - "{{ motd_commands }}"
  - "{{ motd_files }}"
 
- name: Make sure folder exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  with_items:
  - "{{ motd_notes }}"

- name: Install figlet
  yum:
    name: figlet
    state: present

- name: Generate header
  shell: figlet {{ inventory_hostname }}
  register: motd_figlet_header

- name: Create motd
  template:
    src: motd.j2
    dest: "{{ motd_path }}"

- name: Add commands header
  command: printf "\n\nCommands:" >> {{ motd_path }}

- name: Add commands
  command: echo "  - {{ item }}" >> {{ motd_path }}
  with_lines: "{{ motd_commands }}"

- name: Add files header
  command: printf "\n\nFiles:" >> {{ motd_path }}

- name: Add files
  command: echo "  - {{ item }}" >> {{ motd_path }}
  with_lines: "{{ motd_files }}"


- name: Add notes header
  command: printf "\n\n" >> {{ motd_path }}

- name: Add notes
  command: echo "{{ item }}" >> {{ motd_path }}
  with_lines: "{{ motd_notes }}"

...
