---

- name: Make sure files exist
  file:
    path: "{{ item }}"
    state: touch
    mode: 0664
  with_items:
  - "{{ motd_commands }}"
  - "{{ motd_files }}"
#  - "{{ motd_notes }}"

- name: Install figlet
  yum:
    name: figlet
    state: present

- name: Generate header
  shell: figlet {{ inventory_hostname }}
  register: motd_figlet_header

- name: Create motd
  template:
    src: motd.j2
    dest: "{{ motd_path }}"

- name: Add commands header
  command: printf "\n\nCommands:" >> {{ motd_path }}

- name: get commands contents
  command: cat {{ motd_commands }} 
  register: commands_cat
- name: install these items
  command: echo "  - {{ item }}" >> {{ motd_path }}  
  with_items: commands_cat.stdout_lines

- name: Add files header
  command: printf "\n\nFiles:" >> {{ motd_path }}

- name: get files contents
  command: cat {{ motd_files }} 
  register: files_cat
- name: install these items
  command: echo "  - {{ item }}" >> {{ motd_path }}  
  with_items: files_cat.stdout_lines

- name: Add notes header
  command: printf "\n\n" >> {{ motd_path }}

#- name: get notes contents
#  command: cat {{ motd_notes }} 
#  register: notes_cat
#- name: install these items
#  command: echo "{{ item }}" >> {{ motd_path }}  
#  with_items: notes_cat.stdout_lines
...
